# Generated by Django 6.0.2 on 2026-02-24 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careapp', '0003_alter_doctor_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='myAppointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField()),
                ('phone', models.CharField(max_length=20)),
                ('datetime', models.DateTimeField()),
                ('department', models.CharField(max_length=100)),
                ('doctor', models.CharField(max_length=20)),
                ('message', models.TextField()),
            ],
        ),
    ]
