# Generated by Django 6.0.2 on 2026-03-08 10:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careapp', '0006_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='dateemployed',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
